title: Follow Line
description: Documentatión and description of the fourth practice from Embeded and real-time systems subject.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Pablo Sánchez Fernández, Iker Peral del Pino
repo_url: "https://github.com/iperal2021/follow_line_blog"
edit_on_github: true
github_docs_folder: true
logo: "https://raw.githubusercontent.com/iperal2021/empotrados/main/docs/assets/img/arduino-logo.png"
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
